# Application Configuration
spring:
  application:
    name: transaction

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always 