# Production Configuration
spring:
  application:
    name: transaction
  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3600s  # Production cache settings

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: false  # Disable Try it out feature in production
    filter: true
    syntaxHighlight:
      activated: true

# Server Configuration
server:
  port: 80
  error:
    include-message: never  # Hide detailed error messages in production
    include-binding-errors: never
    include-stacktrace: never

# Logging Configuration
logging:
  level:
    root: INFO
    com.hsbc.banking: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 